### PR TITLE
Added in a results page

### PR DESCRIPTION
**Pull request by airborne-commando**
In the results page, you'll be able to see previews of a URL with the images.

### CODE REVIEW

**Comment by airborne-commando** [comment]
image
Example of the results page.

**Comment by airborne-commando** [comment]
Some results don't display, either 404 or insecure connection on the website.

**Comment by airborne-commando** [comment]
Tried to find out where the site would come from and redirect it from there; much like facecheck.id but to no avail. Feel free to accept this pull request. @addycb

**Comment by airborne-commando** [comment]
May add more features in my fork; be sure to check it out in the meantime.

**Comment by addycb** [comment]
> Tried to find out where the site would come from and redirect it from there; much like facecheck.id but to no avail. Feel free to accept this pull request. @addycb

I haven't touched this version of the tool in a while, but I assume you mean the weblink to the original image, if this tool currently only gives the cached version from p1meyes. Though not 100% sure the issue. You should be able to get the image that p1meyes has cached, along with the original link, from the "rgbattack" implementation, which I just cleaned the api keys and made  public here: https://github.com/addycb/facefinder-public . Though it is a bit messy, let me know if you have any q's

**Comment by airborne-commando** [comment]
@addycb I meant when you'd use facecheck ID for a search on someones face it would direct you to the website and the account associated to that face; wanted something like this on pimeyes.
https://github.com/vin3110/facecheck.id-results-extractor use this on your browser, you'll bypass the paywall and will give you the links, tool I also touched on: an example of a result.

https://facecheck.id/#K4bpaAOoZvU (will probably expire; but it's a pic of gabe again)

**Pull request merged**
